server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址，一般不用这种形式
          uri: lb://user-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
          filters: # 过滤器，可以对请求进行一些处理
            - AddRequestHeader=X-Request-Red, blue # 添加请求头，key是X-Request-Red，value是blue
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
      default-filters: # 默认过滤器，会对所有的路由请求都生效
        - AddRequestHeader=X-Request-Default, default
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]': # 所有的请求都生效
            allowedOrigins: # 允许哪些网站跨域请求
              - "http://localhost:8080" # 允许的请求来源
              - "http://www.baidu.com" # 允许的请求来源
            allowedMethods: # 允许哪些请求方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*" # 允许在请求头中携带的信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期，为了减少检测次数，提高性能